[project]
name = "codepic"
version = "0.1.0"
description = "Capture code in a picture"
readme = "README.md"
license = "MIT"
authors = [{ name = "Thomas Harrison", email = "theharrisoncrafter@gmail.com" }]
homepage = "https://github.com/automas-dev/codepic"
repository = "https://github.com/automas-dev/codepic"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
requires-python = ">=3.11"
dependencies = [
    "click>=8.4.0",
    "pillow>=12.2.0",
    "pygments>=2.20.0",
]

# packages = [{ include = "codepic", from = "src" }]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.13",
]

[project.scripts]
codepic = "codepic:cli"

[build-system]
requires = ["uv_build>=0.11.15,<0.12.0"]
build-backend = "uv_build"

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["F401"]

[tool.ruff.format]
quote-style = "single"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "--cov"

[tool.coverage.run]
branch = false
source = ["src"]

[tool.coverage.report]
show_missing = true
fail_under = 100
