name: ci

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint_test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Dependencies
        run: uv sync --locked --all-extras --dev

      - name: Lint
        run: |
          uv run ruff format --check
          uv run ruff check

      # - name: Test
      #   run: uv run pytest

  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'NO RELEASE')

    needs: lint_test

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Increment Version
        uses: automas-dev/reusable-workflows/increment_version@v1.0
        id: version

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Dependencies
        run: uv sync --locked --all-extras --dev

      - name: Set version
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: uv version $VERSION

      - name: Build Release
        run: uv build

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "dist/*.whl"
          makeLatest: true
          generateReleaseNotes: true
          tag: ${{ steps.version.outputs.version }}

      - name: Publish Package
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_KEY }}
        run: uv publish
